apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-microservice
  labels:
    app: ui-microservice
spec:
  replicas: 1
  selector:
   matchLabels:
     app: ui-microservice
  template:
   metadata:
     labels:
      app: ui-microservice
   spec:
    containers:
    - name: ui-microservice
      image: ui-microservice-image-docker:0.0.1
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 5004